DROP TABLE IF EXISTS users, dishes, meals, dishes_on_meal CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(300) NOT NULL,
    email varchar(300) NOT NULL,
    birth_date date NOT NULL,
    weight float NOT NULL,
    height float NOT NULL,
    sex varchar(10) NOT NULL,
    goal varchar(20),
    calories_limit integer,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS dishes (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(500) NOT NULL,
    calories float NOT NULL,
    proteins float NOT NULL,
    fats float NOT NULL,
    carbohydrates float NOT NULL,
    CONSTRAINT pk_dishes PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS meals (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id bigint REFERENCES users(id) on delete cascade,
    created_at timestamp,
    CONSTRAINT pk_meals PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS dishes_on_meal (
    meal_id bigint REFERENCES meals(id) on delete cascade,
    dish_id bigint REFERENCES dishes(id) on delete cascade,
    user_id bigint REFERENCES users(id) on delete cascade,
    weight float NOT NULL,
    calories_total float,
    CONSTRAINT pk_dishes_on_meals PRIMARY KEY (meal_id, dish_id)
);
